<?php
function countriesList(): array {
    return [
        // ── Africa ──────────────────────────────────────────────
        ['code'=>'SL','name'=>'Sierra Leone',              'dial'=>'+232','currency'=>'NLE'],
        ['code'=>'DZ','name'=>'Algeria',                   'dial'=>'+213','currency'=>'DZD'],
        ['code'=>'AO','name'=>'Angola',                    'dial'=>'+244','currency'=>'AOA'],
        ['code'=>'BJ','name'=>'Benin',                     'dial'=>'+229','currency'=>'XOF'],
        ['code'=>'BW','name'=>'Botswana',                  'dial'=>'+267','currency'=>'BWP'],
        ['code'=>'BF','name'=>'Burkina Faso',              'dial'=>'+226','currency'=>'XOF'],
        ['code'=>'BI','name'=>'Burundi',                   'dial'=>'+257','currency'=>'BIF'],
        ['code'=>'CM','name'=>'Cameroon',                  'dial'=>'+237','currency'=>'XAF'],
        ['code'=>'CV','name'=>'Cape Verde',                'dial'=>'+238','currency'=>'CVE'],
        ['code'=>'CF','name'=>'Central African Republic',  'dial'=>'+236','currency'=>'XAF'],
        ['code'=>'TD','name'=>'Chad',                      'dial'=>'+235','currency'=>'XAF'],
        ['code'=>'KM','name'=>'Comoros',                   'dial'=>'+269','currency'=>'KMF'],
        ['code'=>'CG','name'=>'Congo',                     'dial'=>'+242','currency'=>'XAF'],
        ['code'=>'CD','name'=>'DR Congo',                  'dial'=>'+243','currency'=>'CDF'],
        ['code'=>'CI','name'=>'Côte d\'Ivoire',            'dial'=>'+225','currency'=>'XOF'],
        ['code'=>'DJ','name'=>'Djibouti',                  'dial'=>'+253','currency'=>'DJF'],
        ['code'=>'EG','name'=>'Egypt',                     'dial'=>'+20', 'currency'=>'EGP'],
        ['code'=>'GQ','name'=>'Equatorial Guinea',         'dial'=>'+240','currency'=>'XAF'],
        ['code'=>'ER','name'=>'Eritrea',                   'dial'=>'+291','currency'=>'ERN'],
        ['code'=>'ET','name'=>'Ethiopia',                  'dial'=>'+251','currency'=>'ETB'],
        ['code'=>'GA','name'=>'Gabon',                     'dial'=>'+241','currency'=>'XAF'],
        ['code'=>'GM','name'=>'Gambia',                    'dial'=>'+220','currency'=>'GMD'],
        ['code'=>'GH','name'=>'Ghana',                     'dial'=>'+233','currency'=>'GHS'],
        ['code'=>'GN','name'=>'Guinea',                    'dial'=>'+224','currency'=>'GNF'],
        ['code'=>'GW','name'=>'Guinea-Bissau',             'dial'=>'+245','currency'=>'XOF'],
        ['code'=>'KE','name'=>'Kenya',                     'dial'=>'+254','currency'=>'KES'],
        ['code'=>'LS','name'=>'Lesotho',                   'dial'=>'+266','currency'=>'LSL'],
        ['code'=>'LR','name'=>'Liberia',                   'dial'=>'+231','currency'=>'LRD'],
        ['code'=>'LY','name'=>'Libya',                     'dial'=>'+218','currency'=>'LYD'],
        ['code'=>'MG','name'=>'Madagascar',                'dial'=>'+261','currency'=>'MGA'],
        ['code'=>'MW','name'=>'Malawi',                    'dial'=>'+265','currency'=>'MWK'],
        ['code'=>'ML','name'=>'Mali',                      'dial'=>'+223','currency'=>'XOF'],
        ['code'=>'MR','name'=>'Mauritania',                'dial'=>'+222','currency'=>'MRU'],
        ['code'=>'MU','name'=>'Mauritius',                 'dial'=>'+230','currency'=>'MUR'],
        ['code'=>'MA','name'=>'Morocco',                   'dial'=>'+212','currency'=>'MAD'],
        ['code'=>'MZ','name'=>'Mozambique',                'dial'=>'+258','currency'=>'MZN'],
        ['code'=>'NA','name'=>'Namibia',                   'dial'=>'+264','currency'=>'NAD'],
        ['code'=>'NE','name'=>'Niger',                     'dial'=>'+227','currency'=>'XOF'],
        ['code'=>'NG','name'=>'Nigeria',                   'dial'=>'+234','currency'=>'NGN'],
        ['code'=>'RW','name'=>'Rwanda',                    'dial'=>'+250','currency'=>'RWF'],
        ['code'=>'ST','name'=>'São Tomé and Príncipe',     'dial'=>'+239','currency'=>'STN'],
        ['code'=>'SN','name'=>'Senegal',                   'dial'=>'+221','currency'=>'XOF'],
        ['code'=>'SC','name'=>'Seychelles',                'dial'=>'+248','currency'=>'SCR'],
        ['code'=>'SO','name'=>'Somalia',                   'dial'=>'+252','currency'=>'SOS'],
        ['code'=>'ZA','name'=>'South Africa',              'dial'=>'+27', 'currency'=>'ZAR'],
        ['code'=>'SS','name'=>'South Sudan',               'dial'=>'+211','currency'=>'SSP'],
        ['code'=>'SD','name'=>'Sudan',                     'dial'=>'+249','currency'=>'SDG'],
        ['code'=>'SZ','name'=>'Eswatini',                  'dial'=>'+268','currency'=>'SZL'],
        ['code'=>'TZ','name'=>'Tanzania',                  'dial'=>'+255','currency'=>'TZS'],
        ['code'=>'TG','name'=>'Togo',                      'dial'=>'+228','currency'=>'XOF'],
        ['code'=>'TN','name'=>'Tunisia',                   'dial'=>'+216','currency'=>'TND'],
        ['code'=>'UG','name'=>'Uganda',                    'dial'=>'+256','currency'=>'UGX'],
        ['code'=>'ZM','name'=>'Zambia',                    'dial'=>'+260','currency'=>'ZMW'],
        ['code'=>'ZW','name'=>'Zimbabwe',                  'dial'=>'+263','currency'=>'ZWL'],
        // ── Americas ─────────────────────────────────────────────
        ['code'=>'AR','name'=>'Argentina',                 'dial'=>'+54', 'currency'=>'ARS'],
        ['code'=>'BB','name'=>'Barbados',                  'dial'=>'+1',  'currency'=>'BBD'],
        ['code'=>'BZ','name'=>'Belize',                    'dial'=>'+501','currency'=>'BZD'],
        ['code'=>'BO','name'=>'Bolivia',                   'dial'=>'+591','currency'=>'BOB'],
        ['code'=>'BR','name'=>'Brazil',                    'dial'=>'+55', 'currency'=>'BRL'],
        ['code'=>'CA','name'=>'Canada',                    'dial'=>'+1',  'currency'=>'CAD'],
        ['code'=>'CL','name'=>'Chile',                     'dial'=>'+56', 'currency'=>'CLP'],
        ['code'=>'CO','name'=>'Colombia',                  'dial'=>'+57', 'currency'=>'COP'],
        ['code'=>'CR','name'=>'Costa Rica',                'dial'=>'+506','currency'=>'CRC'],
        ['code'=>'CU','name'=>'Cuba',                      'dial'=>'+53', 'currency'=>'CUP'],
        ['code'=>'DO','name'=>'Dominican Republic',        'dial'=>'+1',  'currency'=>'DOP'],
        ['code'=>'EC','name'=>'Ecuador',                   'dial'=>'+593','currency'=>'USD'],
        ['code'=>'SV','name'=>'El Salvador',               'dial'=>'+503','currency'=>'USD'],
        ['code'=>'GT','name'=>'Guatemala',                 'dial'=>'+502','currency'=>'GTQ'],
        ['code'=>'GY','name'=>'Guyana',                    'dial'=>'+592','currency'=>'GYD'],
        ['code'=>'HT','name'=>'Haiti',                     'dial'=>'+509','currency'=>'HTG'],
        ['code'=>'HN','name'=>'Honduras',                  'dial'=>'+504','currency'=>'HNL'],
        ['code'=>'JM','name'=>'Jamaica',                   'dial'=>'+1',  'currency'=>'JMD'],
        ['code'=>'MX','name'=>'Mexico',                    'dial'=>'+52', 'currency'=>'MXN'],
        ['code'=>'NI','name'=>'Nicaragua',                 'dial'=>'+505','currency'=>'NIO'],
        ['code'=>'PA','name'=>'Panama',                    'dial'=>'+507','currency'=>'PAB'],
        ['code'=>'PY','name'=>'Paraguay',                  'dial'=>'+595','currency'=>'PYG'],
        ['code'=>'PE','name'=>'Peru',                      'dial'=>'+51', 'currency'=>'PEN'],
        ['code'=>'PR','name'=>'Puerto Rico',               'dial'=>'+1',  'currency'=>'USD'],
        ['code'=>'TT','name'=>'Trinidad and Tobago',       'dial'=>'+1',  'currency'=>'TTD'],
        ['code'=>'US','name'=>'United States',             'dial'=>'+1',  'currency'=>'USD'],
        ['code'=>'UY','name'=>'Uruguay',                   'dial'=>'+598','currency'=>'UYU'],
        ['code'=>'VE','name'=>'Venezuela',                 'dial'=>'+58', 'currency'=>'VES'],
        // ── Asia ─────────────────────────────────────────────────
        ['code'=>'AF','name'=>'Afghanistan',               'dial'=>'+93', 'currency'=>'AFN'],
        ['code'=>'AM','name'=>'Armenia',                   'dial'=>'+374','currency'=>'AMD'],
        ['code'=>'AZ','name'=>'Azerbaijan',                'dial'=>'+994','currency'=>'AZN'],
        ['code'=>'BH','name'=>'Bahrain',                   'dial'=>'+973','currency'=>'BHD'],
        ['code'=>'BD','name'=>'Bangladesh',                'dial'=>'+880','currency'=>'BDT'],
        ['code'=>'CN','name'=>'China',                     'dial'=>'+86', 'currency'=>'CNY'],
        ['code'=>'GE','name'=>'Georgia',                   'dial'=>'+995','currency'=>'GEL'],
        ['code'=>'HK','name'=>'Hong Kong',                 'dial'=>'+852','currency'=>'HKD'],
        ['code'=>'IN','name'=>'India',                     'dial'=>'+91', 'currency'=>'INR'],
        ['code'=>'ID','name'=>'Indonesia',                 'dial'=>'+62', 'currency'=>'IDR'],
        ['code'=>'IR','name'=>'Iran',                      'dial'=>'+98', 'currency'=>'IRR'],
        ['code'=>'IQ','name'=>'Iraq',                      'dial'=>'+964','currency'=>'IQD'],
        ['code'=>'IL','name'=>'Israel',                    'dial'=>'+972','currency'=>'ILS'],
        ['code'=>'JP','name'=>'Japan',                     'dial'=>'+81', 'currency'=>'JPY'],
        ['code'=>'JO','name'=>'Jordan',                    'dial'=>'+962','currency'=>'JOD'],
        ['code'=>'KZ','name'=>'Kazakhstan',                'dial'=>'+7',  'currency'=>'KZT'],
        ['code'=>'KW','name'=>'Kuwait',                    'dial'=>'+965','currency'=>'KWD'],
        ['code'=>'KG','name'=>'Kyrgyzstan',                'dial'=>'+996','currency'=>'KGS'],
        ['code'=>'LB','name'=>'Lebanon',                   'dial'=>'+961','currency'=>'LBP'],
        ['code'=>'MY','name'=>'Malaysia',                  'dial'=>'+60', 'currency'=>'MYR'],
        ['code'=>'MV','name'=>'Maldives',                  'dial'=>'+960','currency'=>'MVR'],
        ['code'=>'MN','name'=>'Mongolia',                  'dial'=>'+976','currency'=>'MNT'],
        ['code'=>'MM','name'=>'Myanmar',                   'dial'=>'+95', 'currency'=>'MMK'],
        ['code'=>'NP','name'=>'Nepal',                     'dial'=>'+977','currency'=>'NPR'],
        ['code'=>'KP','name'=>'North Korea',               'dial'=>'+850','currency'=>'KPW'],
        ['code'=>'OM','name'=>'Oman',                      'dial'=>'+968','currency'=>'OMR'],
        ['code'=>'PK','name'=>'Pakistan',                  'dial'=>'+92', 'currency'=>'PKR'],
        ['code'=>'PH','name'=>'Philippines',               'dial'=>'+63', 'currency'=>'PHP'],
        ['code'=>'QA','name'=>'Qatar',                     'dial'=>'+974','currency'=>'QAR'],
        ['code'=>'SA','name'=>'Saudi Arabia',              'dial'=>'+966','currency'=>'SAR'],
        ['code'=>'SG','name'=>'Singapore',                 'dial'=>'+65', 'currency'=>'SGD'],
        ['code'=>'KR','name'=>'South Korea',               'dial'=>'+82', 'currency'=>'KRW'],
        ['code'=>'LK','name'=>'Sri Lanka',                 'dial'=>'+94', 'currency'=>'LKR'],
        ['code'=>'SY','name'=>'Syria',                     'dial'=>'+963','currency'=>'SYP'],
        ['code'=>'TW','name'=>'Taiwan',                    'dial'=>'+886','currency'=>'TWD'],
        ['code'=>'TJ','name'=>'Tajikistan',                'dial'=>'+992','currency'=>'TJS'],
        ['code'=>'TH','name'=>'Thailand',                  'dial'=>'+66', 'currency'=>'THB'],
        ['code'=>'TL','name'=>'Timor-Leste',               'dial'=>'+670','currency'=>'USD'],
        ['code'=>'TR','name'=>'Turkey',                    'dial'=>'+90', 'currency'=>'TRY'],
        ['code'=>'TM','name'=>'Turkmenistan',              'dial'=>'+993','currency'=>'TMT'],
        ['code'=>'AE','name'=>'United Arab Emirates',      'dial'=>'+971','currency'=>'AED'],
        ['code'=>'UZ','name'=>'Uzbekistan',                'dial'=>'+998','currency'=>'UZS'],
        ['code'=>'VN','name'=>'Vietnam',                   'dial'=>'+84', 'currency'=>'VND'],
        ['code'=>'YE','name'=>'Yemen',                     'dial'=>'+967','currency'=>'YER'],
        // ── Europe ───────────────────────────────────────────────
        ['code'=>'AL','name'=>'Albania',                   'dial'=>'+355','currency'=>'ALL'],
        ['code'=>'AT','name'=>'Austria',                   'dial'=>'+43', 'currency'=>'EUR'],
        ['code'=>'BY','name'=>'Belarus',                   'dial'=>'+375','currency'=>'BYN'],
        ['code'=>'BE','name'=>'Belgium',                   'dial'=>'+32', 'currency'=>'EUR'],
        ['code'=>'BA','name'=>'Bosnia & Herzegovina',      'dial'=>'+387','currency'=>'BAM'],
        ['code'=>'BG','name'=>'Bulgaria',                  'dial'=>'+359','currency'=>'BGN'],
        ['code'=>'HR','name'=>'Croatia',                   'dial'=>'+385','currency'=>'EUR'],
        ['code'=>'CY','name'=>'Cyprus',                    'dial'=>'+357','currency'=>'EUR'],
        ['code'=>'CZ','name'=>'Czech Republic',            'dial'=>'+420','currency'=>'CZK'],
        ['code'=>'DK','name'=>'Denmark',                   'dial'=>'+45', 'currency'=>'DKK'],
        ['code'=>'EE','name'=>'Estonia',                   'dial'=>'+372','currency'=>'EUR'],
        ['code'=>'FI','name'=>'Finland',                   'dial'=>'+358','currency'=>'EUR'],
        ['code'=>'FR','name'=>'France',                    'dial'=>'+33', 'currency'=>'EUR'],
        ['code'=>'DE','name'=>'Germany',                   'dial'=>'+49', 'currency'=>'EUR'],
        ['code'=>'GR','name'=>'Greece',                    'dial'=>'+30', 'currency'=>'EUR'],
        ['code'=>'HU','name'=>'Hungary',                   'dial'=>'+36', 'currency'=>'HUF'],
        ['code'=>'IS','name'=>'Iceland',                   'dial'=>'+354','currency'=>'ISK'],
        ['code'=>'IE','name'=>'Ireland',                   'dial'=>'+353','currency'=>'EUR'],
        ['code'=>'IT','name'=>'Italy',                     'dial'=>'+39', 'currency'=>'EUR'],
        ['code'=>'XK','name'=>'Kosovo',                    'dial'=>'+383','currency'=>'EUR'],
        ['code'=>'LV','name'=>'Latvia',                    'dial'=>'+371','currency'=>'EUR'],
        ['code'=>'LT','name'=>'Lithuania',                 'dial'=>'+370','currency'=>'EUR'],
        ['code'=>'LU','name'=>'Luxembourg',                'dial'=>'+352','currency'=>'EUR'],
        ['code'=>'MT','name'=>'Malta',                     'dial'=>'+356','currency'=>'EUR'],
        ['code'=>'MD','name'=>'Moldova',                   'dial'=>'+373','currency'=>'MDL'],
        ['code'=>'ME','name'=>'Montenegro',                'dial'=>'+382','currency'=>'EUR'],
        ['code'=>'NL','name'=>'Netherlands',               'dial'=>'+31', 'currency'=>'EUR'],
        ['code'=>'MK','name'=>'North Macedonia',           'dial'=>'+389','currency'=>'MKD'],
        ['code'=>'NO','name'=>'Norway',                    'dial'=>'+47', 'currency'=>'NOK'],
        ['code'=>'PL','name'=>'Poland',                    'dial'=>'+48', 'currency'=>'PLN'],
        ['code'=>'PT','name'=>'Portugal',                  'dial'=>'+351','currency'=>'EUR'],
        ['code'=>'RO','name'=>'Romania',                   'dial'=>'+40', 'currency'=>'RON'],
        ['code'=>'RU','name'=>'Russia',                    'dial'=>'+7',  'currency'=>'RUB'],
        ['code'=>'RS','name'=>'Serbia',                    'dial'=>'+381','currency'=>'RSD'],
        ['code'=>'SK','name'=>'Slovakia',                  'dial'=>'+421','currency'=>'EUR'],
        ['code'=>'SI','name'=>'Slovenia',                  'dial'=>'+386','currency'=>'EUR'],
        ['code'=>'ES','name'=>'Spain',                     'dial'=>'+34', 'currency'=>'EUR'],
        ['code'=>'SE','name'=>'Sweden',                    'dial'=>'+46', 'currency'=>'SEK'],
        ['code'=>'CH','name'=>'Switzerland',               'dial'=>'+41', 'currency'=>'CHF'],
        ['code'=>'UA','name'=>'Ukraine',                   'dial'=>'+380','currency'=>'UAH'],
        ['code'=>'GB','name'=>'United Kingdom',            'dial'=>'+44', 'currency'=>'GBP'],
        // ── Oceania ──────────────────────────────────────────────
        ['code'=>'AU','name'=>'Australia',                 'dial'=>'+61', 'currency'=>'AUD'],
        ['code'=>'FJ','name'=>'Fiji',                      'dial'=>'+679','currency'=>'FJD'],
        ['code'=>'NZ','name'=>'New Zealand',               'dial'=>'+64', 'currency'=>'NZD'],
        ['code'=>'PG','name'=>'Papua New Guinea',          'dial'=>'+675','currency'=>'PGK'],
        ['code'=>'WS','name'=>'Samoa',                     'dial'=>'+685','currency'=>'WST'],
        ['code'=>'TO','name'=>'Tonga',                     'dial'=>'+676','currency'=>'TOP'],
        ['code'=>'VU','name'=>'Vanuatu',                   'dial'=>'+678','currency'=>'VUV'],
    ];
}
